trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- task: CmdLine@2
  inputs:
    script: |
      python -m venv env
      source env/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
      pyinstaller --onefile password_vault.py -w
  displayName: 'Build executable'

- task: CopyFiles@2
  inputs:
    Contents: 'dist/password_vault'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy artifact'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'password_vault'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish artifact'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Pipeline.Workspace)/password_vault'
    azureSubscription: '08fc31e4-b54a-421f-bb17-613757673ba7'
    Destination: 'AzureBlob'
    storage: 'devops2023passwordvault'
    ContainerName: 'passwordvault'
