trigger:
- master

pool: 
  vmImage: ubuntu-latest
  
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- task: CmdLine@2
  inputs:
    script: |
      python -m venv env
      source env/bin/activate
      pip install --upgrade pip
      pip install pyinstaller
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
       env/bin/pyinstaller --onefile password_vault.py -w
  displayName: 'Build executable'

- task: CopyFiles@2
  inputs:
    Contents: 'dist/password_vault'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy artifact'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'password_vault'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish artifact'
  
- task: CmdLine@2
  inputs:
    script: |
       ls $(Build.ArtifactStagingDirectory)/dist
  displayName: 'List artifact items'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github connection 1'
    repositoryName: 'Ixurano/password_vault'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'V.1.0.0'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'